language: go

sudo: false

go:
  - 1.7
  - 1.8

before_install:
  - go get github.com/mattn/goveralls
  - if ! go get github.com/golang/tools/cmd/cover; then go get golang.org/x/tools/cmd/cover; fi

install:
  - go get github.com/spf13/pflag
  - go get github.com/golang/snappy
  - go get github.com/hashicorp/go-version

script:
  - go test -v -covermode=count -coverprofile=coverage.out
  - $HOME/gopath/bin/goveralls -coverprofile=coverage.out -service=travis-ci
